@SpeechRecognition.WebAPI_HostAddress = https://localhost:7201

POST {{SpeechRecognition.WebAPI_HostAddress}}/speechrecognition/
Accept: application/json

GET {{SpeechRecognition.WebAPI_HostAddress}}/commands/
Accept: application/json

###
